/* I18N DOMAIN — English / Hindi / Marathi. Any text in TR is translated automatically; new text can simply be added to TR. */
const LANGS={en:'English',hi:'हिन्दी',mr:'मराठी'};let lang=LS.getItem('salon_lang')||'en';
const TR={'Welcome to Glamglow Unisex Saloon': ['ग्लैमग्लो यूनिसेक्स सैलून में आपका स्वागत है', 'ग्लॅमग्लो युनिसेक्स सलूनमध्ये आपले स्वागत आहे'], 'Choose your language': ['अपनी भाषा चुनें', 'तुमची भाषा निवडा'], 'Please login or register to continue': ['जारी रखने के लिए लॉगिन या रजिस्टर करें', 'पुढे जाण्यासाठी लॉगिन किंवा नोंदणी करा'], 'Login': ['लॉगिन', 'लॉगिन'], 'Register': ['रजिस्टर', 'नोंदणी'], 'Customer Login': ['ग्राहक लॉगिन', 'ग्राहक लॉगिन'], 'Name or Mobile Number': ['नाम या मोबाइल नंबर', 'नाव किंवा मोबाइल नंबर'], 'Password': ['पासवर्ड', 'पासवर्ड'], 'Full Name': ['पूरा नाम', 'पूर्ण नाव'], 'Mobile Number': ['मोबाइल नंबर', 'मोबाइल नंबर'], 'Email ID': ['ईमेल आईडी', 'ईमेल आयडी'], 'Register & Continue': ['रजिस्टर करें और आगे बढ़ें', 'नोंदणी करा आणि पुढे जा'], 'Show password': ['पासवर्ड दिखाएँ', 'पासवर्ड दाखवा'], 'View live seats & timings (no login needed)': ['लाइव सीट और समय देखें (लॉगिन ज़रूरी नहीं)', 'लाइव्ह सीट आणि वेळ पहा (लॉगिन आवश्यक नाही)'], 'Live seats & timings': ['लाइव सीट और समय', 'लाइव्ह सीट आणि वेळ'], 'Welcome,': ['स्वागत है,', 'स्वागत,'], 'Home': ['होम', 'मुख्यपृष्ठ'], 'Book': ['बुकिंग', 'बुकिंग'], 'Seats & Timings': ['सीट और समय', 'सीट आणि वेळ'], 'Payment': ['भुगतान', 'पेमेंट'], 'History': ['इतिहास', 'इतिहास'], 'Logout': ['लॉगआउट', 'लॉगआउट'], 'Live Queue': ['लाइव कतार', 'लाइव्ह रांग'], 'My Bookings': ['मेरी बुकिंग', 'माझ्या बुकिंग'], 'Choose services': ['सेवाएँ चुनें', 'सेवा निवडा'], 'Pick date & time': ['तारीख और समय चुनें', 'तारीख आणि वेळ निवडा'], 'Choose stylist': ['स्टाइलिस्ट चुनें', 'स्टायलिस्ट निवडा'], 'Choose seat': ['सीट चुनें', 'सीट निवडा'], 'Payment option': ['भुगतान विकल्प', 'पेमेंट पर्याय'], 'Confirm Booking': ['बुकिंग पक्की करें', 'बुकिंग निश्चित करा'], 'Date': ['तारीख', 'तारीख'], 'Service length': ['सेवा अवधि', 'सेवा कालावधी'], 'Available': ['उपलब्ध', 'उपलब्ध'], 'Booked': ['बुक', 'बुक'], 'Blocked': ['बंद', 'बंद'], 'seats left': ['सीट बाकी', 'जागा शिल्लक'], 'Hairstyle': ['हेयरस्टाइल', 'हेअरस्टाइल'], 'Facial': ['फेशियल', 'फेशियल'], 'Hair Colour': ['हेयर कलर', 'हेअर कलर'], 'Beauty & Care': ['ब्यूटी और केयर', 'ब्युटी आणि केअर'], 'Female': ['महिला', 'महिला'], 'Male': ['पुरुष', 'पुरुष'], 'Pick a time first': ['पहले समय चुनें', 'आधी वेळ निवडा'], 'QR code': ['QR कोड', 'QR कोड'], 'Cash': ['नकद', 'रोख'], 'Next available time': ['अगला उपलब्ध समय', 'पुढील उपलब्ध वेळ']};
const EX=[
['Letters only','केवल अक्षर','फक्त अक्षरे'],['10 digits','10 अंक'],['Service name','सेवा का नाम','सेवेचे नाव'],['Staff name','स्टाफ का नाम','कर्मचाऱ्याचे नाव'],['Name / mobile / token','नाम / मोबाइल / टोकन','नाव / मोबाइल / टोकन'],
['At least 8 characters with letters, numbers and symbols.','कम से कम 8 अक्षर: अक्षर, अंक और चिह्न मिलाकर।','किमान 8 अक्षरे: अक्षरे, अंक आणि चिन्हे मिसळून.'],
['New here? Use the Register tab.','नए हैं? रजिस्टर टैब चुनें।','नवीन आहात? नोंदणी टॅब निवडा.'],
['Admin Login','एडमिन लॉगिन','ॲडमिन लॉगिन'],['Username','यूज़रनेम','युजरनेम'],['Login as Admin','एडमिन के रूप में लॉगिन करें','ॲडमिन म्हणून लॉगिन करा'],
['Name must contain letters only (no numbers or symbols).','नाम में केवल अक्षर होने चाहिए (अंक या चिह्न नहीं)।','नावात फक्त अक्षरे असावीत (अंक किंवा चिन्हे नकोत).'],
['Mobile number must be exactly 10 digits.','मोबाइल नंबर ठीक 10 अंकों का होना चाहिए।','मोबाइल नंबर अचूक 10 अंकी असावा.'],
['Email must end with @gmail.com','ईमेल @gmail.com पर खत्म होना चाहिए','ईमेल @gmail.com ने संपला पाहिजे'],
['Password needs 8+ characters with letters, numbers and symbols (example: Salon@123).','पासवर्ड में 8+ अक्षर, अंक और चिह्न चाहिए (उदाहरण: Salon@123)।','पासवर्डमध्ये 8+ अक्षरे, अंक आणि चिन्हे हवीत (उदा. Salon@123).'],
['Mobile already registered. Please login.','मोबाइल पहले से रजिस्टर है। कृपया लॉगिन करें।','मोबाइल आधीच नोंदणीकृत आहे. कृपया लॉगिन करा.'],
['No account found. Please register.','खाता नहीं मिला। कृपया रजिस्टर करें।','खाते सापडले नाही. कृपया नोंदणी करा.'],
['Several accounts share that name — login with your mobile number.','इस नाम के कई खाते हैं — मोबाइल नंबर से लॉगिन करें।','या नावाची अनेक खाती आहेत — मोबाइल नंबरने लॉगिन करा.'],
['Wrong password.','गलत पासवर्ड।','चुकीचा पासवर्ड.'],['Invalid admin credentials.','एडमिन की जानकारी गलत है।','ॲडमिनची माहिती चुकीची आहे.'],
['Registered successfully!','सफलतापूर्वक रजिस्टर हुआ!','यशस्वीरित्या नोंदणी झाली!'],
['Select at least one service.','कम से कम एक सेवा चुनें।','किमान एक सेवा निवडा.'],['Pick a time slot.','समय चुनें।','वेळ निवडा.'],
['Choose a payment option: QR code or Cash.','भुगतान विकल्प चुनें: QR कोड या नकद।','पेमेंट पर्याय निवडा: QR कोड किंवा रोख.'],
['That time has already passed. Pick another slot.','वह समय बीत चुका है। दूसरा समय चुनें।','ती वेळ निघून गेली आहे. दुसरी वेळ निवडा.'],
['You already have a booking at that time.','उस समय आपकी बुकिंग पहले से है।','त्या वेळी तुमची बुकिंग आधीच आहे.'],
['No seat is free at that time. Pick another slot.','उस समय कोई सीट खाली नहीं है। दूसरा समय चुनें।','त्या वेळी कोणतीही सीट रिकामी नाही. दुसरी वेळ निवडा.'],
['That stylist is busy at that time. Pick another.','वह स्टाइलिस्ट उस समय व्यस्त है। दूसरा चुनें।','तो स्टायलिस्ट त्या वेळी व्यस्त आहे. दुसरा निवडा.'],
['Booking cancelled — seat released.','बुकिंग रद्द — सीट खाली कर दी गई।','बुकिंग रद्द — सीट मोकळी केली.'],
['Select a service first.','पहले सेवा चुनें।','आधी सेवा निवडा.'],['No free time on this date — try another date.','इस तारीख पर समय खाली नहीं — दूसरी तारीख आज़माएँ।','या तारखेला वेळ रिकामी नाही — दुसरी तारीख वापरा.'],
['Payment noted — the owner will confirm it.','भुगतान दर्ज हुआ — मालिक पुष्टि करेंगे।','पेमेंट नोंदवले — मालक खात्री करतील.'],['Payment confirmed.','भुगतान की पुष्टि हुई।','पेमेंटची खात्री झाली.'],
['This seat has current or upcoming bookings.','इस सीट पर मौजूदा या आने वाली बुकिंग है।','या सीटवर सध्याची किंवा पुढची बुकिंग आहे.'],['Keep at least one seat.','कम से कम एक सीट रखें।','किमान एक सीट ठेवा.'],
["Only today's bookings can be started.",'केवल आज की बुकिंग शुरू हो सकती है।','फक्त आजची बुकिंग सुरू करता येते.'],['No free seat right now.','अभी कोई सीट खाली नहीं है।','सध्या कोणतीही सीट रिकामी नाही.'],
['Service completed — seat is free for the next customer.','सेवा पूरी — सीट अगले ग्राहक के लिए खाली।','सेवा पूर्ण — सीट पुढच्या ग्राहकासाठी मोकळी.'],['Enter a valid number.','सही संख्या दर्ज करें।','योग्य संख्या टाका.'],['Updated.','अपडेट हो गया।','अपडेट झाले.'],['Price and time must be positive.','कीमत और समय शून्य से अधिक होने चाहिए।','किंमत आणि वेळ शून्यापेक्षा जास्त हवी.'],
['booked','बुक'],['serving','सेवा में','सेवेत'],['completed','पूरा','पूर्ण'],['cancelled','रद्द'],['Paid','भुगतान हुआ','पेमेंट झाले'],['Pending','बाकी','प्रलंबित'],
['Token','टोकन'],['When','कब','केव्हा'],['Services','सेवाएँ','सेवा'],['Seat','सीट'],['Amount','रकम','रक्कम'],['Method','तरीका','पद्धत'],['Status','स्थिति','स्थिती'],
['Seats right now','अभी की सीटें','सध्याच्या सीट'],['Seats left by time','समय के अनुसार बची सीटें','वेळेनुसार शिल्लक सीट'],['My Visit History','मेरी विज़िट का इतिहास','माझा भेट इतिहास'],
['Bookings by seat (one after another)','सीट के अनुसार बुकिंग (एक के बाद एक)','सीटनुसार बुकिंग (एकानंतर एक)'],['Free all day','पूरे दिन खाली','दिवसभर रिकामी'],
['✅ Booking confirmed','✅ बुकिंग पक्की हुई','✅ बुकिंग निश्चित झाली'],['Payment received ✅','भुगतान मिल गया ✅','पेमेंट मिळाले ✅'],
['No upcoming bookings. Go to “Book” to reserve your time.','कोई आगामी बुकिंग नहीं। समय बुक करने के लिए “बुकिंग” पर जाएँ।','पुढील बुकिंग नाही. वेळ राखण्यासाठी “बुकिंग” वर जा.'],
['No pending payments.','कोई बकाया भुगतान नहीं।','प्रलंबित पेमेंट नाही.'],['No visits yet.','अभी कोई विज़िट नहीं।','अद्याप भेट नाही.'],['No more time slots left on this day.','इस दिन कोई समय शेष नहीं।','या दिवशी वेळ शिल्लक नाही.'],
['Choose a service to see available times.','उपलब्ध समय देखने के लिए सेवा चुनें।','उपलब्ध वेळ पाहण्यासाठी सेवा निवडा.'],['Select one or more services — each has its own time.','एक या अधिक सेवाएँ चुनें — हर सेवा का अपना समय है।','एक किंवा अधिक सेवा निवडा — प्रत्येकाची स्वतंत्र वेळ आहे.'],
['Layer Cut','लेयर कट'],['Bob Cut','बॉब कट'],['Step Cut','स्टेप कट'],['Pixie Cut','पिक्सी कट'],['Blow Dry','ब्लो ड्राई'],['Curls & Waves','कर्ल्स और वेव्स','कर्ल्स आणि वेव्स'],['Fade Cut','फेड कट'],['Crew Cut','क्रू कट'],['Undercut','अंडरकट'],['Pompadour','पॉम्पाडोर'],
['Beard Styling','दाढ़ी स्टाइलिंग','दाढी स्टायलिंग'],['Kids Haircut','बच्चों का हेयरकट','मुलांचा हेअरकट'],['Fruit Facial','फ्रूट फेशियल'],['Gold Facial','गोल्ड फेशियल'],['Diamond Facial','डायमंड फेशियल'],['Charcoal Detox','चारकोल डिटॉक्स'],['Anti-Tan Facial','एंटी-टैन फेशियल'],['Hydra Glow','हाइड्रा ग्लो'],["Men's Clean-up",'पुरुष क्लीन-अप'],
['Global Colour','ग्लोबल कलर'],['Highlights','हाइलाइट्स'],['Root Touch-up','रूट टच-अप'],['Balayage','बालयाज'],['Hair Wash','हेयर वॉश','हेअर वॉश'],['Head Massage','सिर की मालिश','डोक्याची मालिश'],['Eyebrow Threading','आईब्रो थ्रेडिंग','आयब्रो थ्रेडिंग'],
['Manicure','मैनिक्योर','मॅनिक्युअर'],['Pedicure','पेडीक्योर','पेडिक्युअर'],['Waxing','वैक्सिंग','वॅक्सिंग'],['Bridal Makeup','ब्राइडल मेकअप'],
['Priya','प्रिया'],['Anjali','अंजली'],['Sneha','स्नेहा'],['Pooja','पूजा'],['Kavya','काव्या'],['Ravi','रवि'],['Amit','अमित'],['Rahul','राहुल'],['Sagar','सागर'],['Vikas','विकास'],
['Admin Dashboard','एडमिन डैशबोर्ड','ॲडमिन डॅशबोर्ड'],['Overview','सारांश'],['Bookings & Queue','बुकिंग और कतार','बुकिंग आणि रांग'],['Schedule','समय-सारणी','वेळापत्रक'],['Seats','सीटें','सीट'],['Staff','स्टाफ','कर्मचारी'],['Customers','ग्राहक'],['Payments & Reports','भुगतान और रिपोर्ट','पेमेंट आणि अहवाल'],
['Registered Customers','पंजीकृत ग्राहक','नोंदणीकृत ग्राहक'],['Waiting Today','आज प्रतीक्षा में','आज प्रतीक्षेत'],['Seats Free Now','अभी खाली सीटें','सध्या रिकाम्या सीट'],['In Service','सेवा में','सेवेत'],["Today's Revenue",'आज की कमाई','आजची कमाई'],['Pending Payments','बकाया भुगतान','प्रलंबित पेमेंट'],
['Waiting','प्रतीक्षा में','प्रतीक्षेत'],['In Service (Completing)','सेवा में (पूरी होने वाली)','सेवेत (पूर्ण होत आहे)'],['Payment Pending','भुगतान बाकी','पेमेंट प्रलंबित'],['No one waiting.','कोई प्रतीक्षा में नहीं।','कोणी प्रतीक्षेत नाही.'],['No one being served.','कोई सेवा में नहीं।','कोणाची सेवा सुरू नाही.'],
['Start','शुरू करें','सुरू करा'],['Complete','पूरा करें','पूर्ण करा'],['Cancel','रद्द करें','रद्द करा'],['Mark Paid','भुगतान दर्ज करें','पेमेंट झाले'],['Confirm payment','भुगतान की पुष्टि','पेमेंटची खात्री'],['Confirm','पुष्टि करें','खात्री करा'],['Delete','हटाएँ','हटवा'],['Toggle','बदलें','बदला'],
['Add Service','सेवा जोड़ें','सेवा जोडा'],['Add Staff','स्टाफ जोड़ें','कर्मचारी जोडा'],['+ Add Seat','+ सीट जोड़ें','+ सीट जोडा'],['− Remove Last Seat','− आख़िरी सीट हटाएँ','− शेवटची सीट हटवा'],
['Customer','ग्राहक'],['Actions','कार्य','कार्ये'],['Availability','उपलब्धता'],['Busy / off','व्यस्त / बंद'],['Name','नाम','नाव'],['Mobile','मोबाइल'],['Email','ईमेल'],['Visits','विज़िट','भेटी'],['Total Paid','कुल भुगतान','एकूण दिलेले'],
['Search','खोजें','शोधा'],['Show','दिखाएँ','दाखवा'],['Today','आज'],['All dates','सभी तारीखें','सर्व तारखा'],['Schedule by seat','सीट के अनुसार समय-सारणी','सीटनुसार वेळापत्रक'],['Bookings & Queue','बुकिंग और कतार','बुकिंग आणि रांग'],
['Paid Today','आज भुगतान हुआ','आज मिळालेले'],['Pending Today','आज बाकी','आज प्रलंबित'],['Total Revenue (All Time)','कुल कमाई (सभी समय)','एकूण कमाई (सर्व काळ)'],['Payment history','भुगतान इतिहास','पेमेंट इतिहास'],['Service','सेवा'],['Time','समय','वेळ'],['Count','गिनती','संख्या'],['Revenue','कमाई'],
['Seat Management (click a free seat to block / unblock)','सीट प्रबंधन (खाली सीट पर क्लिक करके बंद/चालू करें)','सीट व्यवस्थापन (रिकाम्या सीटवर क्लिक करून बंद/चालू करा)'],['Services & timings','सेवाएँ और समय','सेवा आणि वेळ'],['Remember me on this device','इस डिवाइस पर मुझे याद रखें','या डिव्हाइसवर मला लक्षात ठेवा'],['Mobile, Email or Name','मोबाइल, ईमेल या नाम','मोबाइल, ईमेल किंवा नाव'],['Refund pending','रिफंड बाकी','रिफंड प्रलंबित'],['It will be returned by QR/UPI payment.','यह QR/UPI भुगतान से वापस किया जाएगा।','हे QR/UPI पेमेंटने परत केले जाईल.'],['It will be returned in cash at the counter.','यह काउंटर पर नकद वापस किया जाएगा।','हे काउंटरवर रोख परत केले जाईल.'],
['Refunded','वापस किया गया','परत केले'],['Mark Refunded','रिफंड दिया, दर्ज करें','रिफंड दिले, नोंदवा'],['Refunds Pending','बकाया रिफंड','प्रलंबित रिफंड'],
['Cancel this paid booking? The amount will be refunded to the customer.','यह भुगतान की हुई बुकिंग रद्द करें? रकम ग्राहक को वापस की जाएगी।','ही पेमेंट झालेली बुकिंग रद्द करायची? रक्कम ग्राहकाला परत दिली जाईल.'],['Refund marked as returned to the customer.','रिफंड ग्राहक को लौटाया गया दर्ज हुआ।','रिफंड ग्राहकाला परत दिल्याची नोंद झाली.']];
EX.forEach(a=>TR[a[0]]=[a[1],a[2]||a[1]]);
const PH=[['Booking cancelled — refund of ₹','बुकिंग रद्द — रिफंड ₹','बुकिंग रद्द — रिफंड ₹'],[' will be returned to you.',' आपको वापस मिलेगा।',' तुम्हाला परत मिळेल.'],['Refund ₹','रिफंड ₹'],['Booked! Token ','बुक हो गया! टोकन ','बुक झाले! टोकन '],['Salon closes at ','सैलून बंद होता है: ','सलून बंद होते: '],['⏰ Your turn is approaching — token ','⏰ आपकी बारी नज़दीक है — टोकन ','⏰ तुमची पाळी जवळ आली — टोकन '],
['Token ','टोकन '],['Now serving:','अभी सेवा में:','आता सेवेत:'],['Up next:','अगला:','पुढील:'],['Queue position:','कतार में स्थान:','रांगेतील स्थान:'],['people ahead:','आगे लोग:','पुढे लोक:'],['est. wait ~','अनुमानित प्रतीक्षा ~','अंदाजे प्रतीक्षा ~'],[' of ',' / '],
['You are being served now at ','आपकी सेवा अभी हो रही है: ','तुमची सेवा आता सुरू आहे: '],['Your turn is approaching!','आपकी बारी नज़दीक है!','तुमची पाळी जवळ आली आहे!'],['Starts in ','शुरू होगा ','सुरू होईल '],['It is your time now','अब आपका समय है','आता तुमची वेळ आहे'],
['Cancel booking','बुकिंग रद्द करें','बुकिंग रद्द करा'],['Pay by QR code','QR कोड से भुगतान','QR कोडने पेमेंट'],['Pay by Cash','नकद भुगतान','रोख पेमेंट'],["I've paid",'मैंने भुगतान किया','मी पेमेंट केले'],
['Scan with any UPI app and pay ','किसी भी UPI ऐप से स्कैन करके भुगतान करें ','कोणत्याही UPI ॲपने स्कॅन करून पेमेंट करा '],['Pay ₹','भुगतान ₹','पेमेंट ₹'],[' in cash at the counter. The owner will confirm it.',' नकद काउंटर पर दें। मालिक पुष्टि करेंगे।',' रोख काउंटरवर द्या. मालक खात्री करतील.'],
['Amount ₹','रकम ₹','रक्कम ₹'],['QR code','QR कोड'],['Cash','नकद','रोख'],['Total: ','कुल: ','एकूण: '],['Time needed: ','आवश्यक समय: ','लागणारा वेळ: '],['Your slot: ','आपका स्लॉट: ','तुमची वेळ: '],
['Open ','खुला: ','उघडे: '],['Total seats:','कुल सीट:','एकूण सीट:'],['usable:','उपयोग योग्य:','वापरण्यायोग्य:'],['free right now:','अभी खाली:','सध्या रिकाम्या:'],['Slots are for a ','स्लॉट ','स्लॉट '],['-minute service.',' मिनट की सेवा के लिए हैं।',' मिनिटांच्या सेवेसाठी आहेत.'],
['Seat ','सीट '],['Seat added — total ','सीट जोड़ी — कुल ','सीट जोडली — एकूण '],['Seat removed — total ','सीट हटाई — कुल ','सीट हटवली — एकूण '],[' blocked',' बंद की गई',' बंद केली'],[' unblocked',' चालू की गई',' चालू केली'],
[' is now being served.',' की सेवा शुरू हुई।',' यांची सेवा सुरू झाली.'],[' min',' मिनट']].sort((a,b)=>b[0].length-a[0].length);
function tr(s){if(lang==='en')return s;const m=s.match(/^([^\p{L}]*)(\p{L}[^]*?)(\s*)$/u);if(m&&TR[m[2]])return m[1]+T(m[2])+m[3];if(lang==='en')return s;
  const i=lang==='hi'?1:2;PH.forEach(p=>{if(s.includes(p[0]))s=s.split(p[0]).join(p[i]||p[1])});return s}
const T=s=>{const v=TR[s];return v&&lang!=='en'?v[lang==='hi'?0:1]:tr(s)};
const rawText=new WeakMap();
function applyLang(){const w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n;
  while(n=w.nextNode()){const p=n.parentNode.nodeName;if(p==='SCRIPT'||p==='STYLE')continue;
    const raw=rawText.get(n)||n.nodeValue;if(raw.length>200)continue;rawText.set(n,raw);const nv=tr(raw);if(n.nodeValue!==nv)n.nodeValue=nv}
  document.querySelectorAll('[placeholder]').forEach(e=>{const o=e.dataset.ph||(e.dataset.ph=e.placeholder);e.placeholder=tr(o)})}
let _q=0;new MutationObserver(()=>{if(!_q)_q=requestAnimationFrame(()=>{_q=0;applyLang()})}).observe(document.body,{childList:true,subtree:true});
function setLang(l){lang=l;LS.setItem('salon_lang',l);document.documentElement.lang=l;document.querySelectorAll('.langSel').forEach(s=>s.value=l);applyLang()}
function pickLang(l){setLang(l);$('langStep').style.display='none';$('loginStep').style.display='block'}
function resetWelcome(){$('langStep').style.display='block';$('loginStep').style.display='none'}
function goAuth(tab){showScreen('authScreen');document.querySelector('.tab-btn[data-tab='+tab+']').click()}
document.querySelectorAll('.langSel').forEach(s=>{s.innerHTML=Object.entries(LANGS).map(([k,v])=>`<option value="${k}">${v}</option>`).join('');s.value=lang;s.addEventListener('change',()=>setLang(s.value))});
document.documentElement.lang=lang;applyLang();
